[settings]
idiomatic_version_file_enable_tools = []

[tools]
github-cli = "latest"
gitleaks = "8.30.0"
lefthook = "latest"
go = "1.25.5"
golangci-lint = "v2.7.2"
node = "25.2.1"
opencode = "latest"
opentofu = "1.11.0"
postgres = "17.8"
python = "3.12.12"
viddy = "latest"
rust = "1.95.0"
"github:terraform-linters/tflint" = "0.60.0"
